CREATE TABLESPACE MID_TERM DATAFILE
'/datafileParcial@01.dbf' SIZE 50M;


CREATE USER ESTEFANIA
IDENTIFIED BY ESTEFANIA
QUOTA UNLIMITED ON MID_TERM
DEFAULT TABLESPACE MID_TERM;

GRANT CONNECT TO ESTEFANIA;

GRANT DBA TO ESTEFANIA;

CREATE SEQUENCE COMUNAS_SEQ
START WITH 50
INCREMENT BY 3
NOCYCLE;

CREATE SEQUENCE COLEGIOS_SEQ
START WITH 100
INCREMENT BY 1
NOCYCLE;

SELECT COLEGIOS_SEQ.NEXTVAL FROM DUAL;

SELECT COLEGIOS_SEQ.CURRVAL FROM DUAL;

SELECT COMUNAS_SEQ.NEXTVAL FROM DUAL;

SELECT COMUNAS_SEQ.CURRVAL FROM DUAL;

CREATE TABLE COMUNAS (
	ID INTEGER PRIMARY KEY,
	NOMBRE VARCHAR2(255)
)

INSERT INTO COMUNAS VALUES (1,	'POPULAR');
INSERT INTO COMUNAS VALUES (10,	'LA CANDELARIA');
INSERT INTO COMUNAS VALUES (11,	'LAURELES ESTADIO');
INSERT INTO COMUNAS VALUES (12,	'LA AMERICA');
INSERT INTO COMUNAS VALUES (13,	'SAN JAVIER');
INSERT INTO COMUNAS VALUES (14,	'POBLADO');
INSERT INTO COMUNAS VALUES (15,	'GUAYABAL');
INSERT INTO COMUNAS VALUES (16,	'BELÉN');
INSERT INTO COMUNAS VALUES (2,	'SANTA CRUZ');
INSERT INTO COMUNAS VALUES (3,	'MANRIQUE');
INSERT INTO COMUNAS VALUES (4,	'ARANJUEZ');
INSERT INTO COMUNAS VALUES (5,	'CASTILLA');
INSERT INTO COMUNAS VALUES (50,	'PALMITAS');
INSERT INTO COMUNAS VALUES (6,	'DOCE DE OCTUBRE');
INSERT INTO COMUNAS VALUES (60,	'SAN CRISTOBAL');
INSERT INTO COMUNAS VALUES (7,	'ROBLEDO');
INSERT INTO COMUNAS VALUES (70,	'ALTAVISTA');
INSERT INTO COMUNAS VALUES (8,	'VILLA HERMOSA');
INSERT INTO COMUNAS VALUES (80,	'SAN ANTONIO DE PRADO');
INSERT INTO COMUNAS VALUES (9,	'BUENOS AIRES');
INSERT INTO COMUNAS VALUES (90,	'SANTA ELENA');

create table colegios (
    colegios_id numeric(10) not null,
	consecutivo_dane VARCHAR2(255),
	nombre_sede VARCHAR2(255),
	tipo_sede VARCHAR2(255),
	comuna_id INTEGER,
	prestacion_servicio VARCHAR2(255),
	zona VARCHAR2(255),
	barrio VARCHAR2(255),
	sector VARCHAR2(255),
	direccion_sede VARCHAR2(255),
	telefono_sede VARCHAR2(255),
	rector VARCHAR2(255),
	contador_prejardin_jardin INTEGER,
	contador_transicion INTEGER,
	contador_primaria INTEGER,
	contador_secundaria INTEGER,
	contador_media INTEGER,
	contador_adultos INTEGER,
	jornada_completa VARCHAR(8),
	jornada_manana VARCHAR(8),
	jornada_tarde VARCHAR(8),
	jornada_nocturna VARCHAR(8),
	jornada_fin_de_semana VARCHAR(8),
	jornada_unica VARCHAR(8),
	clasificacion_icfes VARCHAR(8),
    CONSTRAINT colegios_pk PRIMARY KEY (colegios_id),
    CONSTRAINT COMUNA_FK
    FOREIGN KEY (colegios_id)
    REFERENCES colegios(colegios_id)
)

Traiga el nombre del barrio y el número de colegios ubicados en cada barrio de aquellas instituciones ubicadas en la comuna de 
buenos aires ordenado por el número de colegios de mayor a menor.

select barrio,
ROUND(COUNT(colegios_id) OVER (PARTITION BY comuna_id)) as numero_colegios
FROM colegios WHERE (comuna_id = 9)
order by NUMERO_COLEGIOS DESC;



 




